#!/bin/sh

export PATH="$PATH:`pwd`/layers/oe-core/bitbake/bin"

cat <<EOF
You had no conf/local.conf file. This configuration file has therefore been
created for you with some default values. You may wish to edit it to, for
example, select a different MACHINE (target hardware). See conf/local.conf
for more information as common configuration options are commented.

You had no conf/bblayers.conf file. This configuration file has therefore been
created for you with some default values. To add additional metadata layers
into your configuration please add entries to conf/bblayers.conf.

The Yocto Project has extensive documentation about OE including a reference
manual which can be found at:
    http://yoctoproject.org/documentation

For more information about OpenEmbedded see their website:
    http://www.openembedded.org/

This project was configured with the following options:
    --machines qemux86-64

Common Wind River images are:
    wrlinux-image-glibc-small     (requires distro: wrlinux-small)
    wrlinux-image-glibc-core      (suggests distro: wrlinux)
    wrlinux-image-glibc-std       (suggests distro: wrlinux)
    wrlinux-image-glibc-std-sato  (requires distro: wrlinux-std-sato)

Common Yocto Project images, typically built with distro poky, are:
    core-image-minimal
    core-image-base
    core-image-sato

You can also run generated qemu images with a command like 'runqemu qemux86-64'
EOF

cd build

