#!/bin/sh

# bitbake simulator

if [ "-g" = "$1" ] ; then
	# bitbake -g curl
	cat <<EOCURL
Loading cache: 100% |############################################| Time: 0:00:02
Loaded 6363 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies
NOTE: PN build list saved to 'pn-buildlist'
NOTE: Task dependencies saved to 'task-depends.dot'
NOTE: Flattened recipe dependencies saved to 'recipe-depends.dot'

Summary: There was 1 WARNING message shown.
EOCURL
	cp ../bin/recipe-depends.dot .
	#echo '"curl" -> "ca-certificates"' >> recipe-depends.dot

elif [ "lib32-wrlinux-image-glibc-core" = "$1" -a "populate_sdk" = "$3" ] ; then
	# bitbake lib32-wrlinux-image-glibc-core -c populate_sdk
	cat <<EOPOP
ERROR: Task do_populate_sdk does not exist for target lib32-wrlinux-image-glibc-core
  (virtual:multilib:lib32:/home/kkang/buildarea/WRLX-20181031/repo/layers/wrlinux/wrlinux-distro/recipes-base/images/wrlinux-image-glibc-core.bb:do_populate_sdk).
  Close matches:
     do_populate_lic
     do_populate_lic_deploy
  ERROR: Command execution failed: 1
EOPOP

elif [ "lib32-wrlinux-image-glibc-core" = "$1" ] ; then
	# bitbake lib32-wrlinux-image-glibc-core
	sleep 2
	cat <<EOL_BUILD1
Currently  5 running tasks (1702 of 2802)  60% |##################             |
0: glibc-2.28-r0 do_install - 220s (pid 25109)
1: qemu-native-3.0.0-r0 do_compile - 185s (pid 12406)
2: lib32-glibc-2.28-r0 do_install - 178s (pid 15858)
3: opkg-native-1_0.3.6-r0 do_configure - 50s (pid 18147)
4: gobject-introspection-native-1.58.0-r0 do_populate_sysroot - 18s (pid 24964)
...
EOL_BUILD1
	sleep 2
	cat <<EOL_BUILD2
Currently 21 running tasks (2351 of 2802)  83% |#########################      |
EOL_BUILD2
	sleep 2
	cat <<EOL_BUILD3
NOTE: Tasks Summary: Attempted 2802 tasks of which 14 didn't need to be rerun and all succeeded.

Summary: There was 1 WARNING message shown.
EOL_BUILD3
	mkdir -p tmp-glibc/deploy/images
	mkdir -p tmp-glibc/deploy/licenses
	mkdir -p tmp-glibc/deploy/rpm

elif [ "wrlinux-image-glibc-core" = "$1" ] ; then
	#bitbake wrlinux-image-glibc-core -c populate_sdk
	sleep 2
	cat <<EOL_BUILD4
Currently 21 running tasks (1412 of 3245)  43% |#############                  |
0: binutils-crosssdk-x86_64-wrlinuxsdk-linux-2.31-r0 do_configure - 288s (pid 25512)
1: gcc-runtime-8.2.0-r0 do_configure - 229s (pid 5517)
2: glibc-locale-2.28-r0 do_package - 161s (pid 14068)
3: nativesdk-perl-5.24.4-r0 do_unpack - 115s (pid 20160)
4: nativesdk-cmake-3.12.2-r0 do_unpack - 79s (pid 27891)
5: busybox-1.29.2-r0 do_unpack - 79s (pid 27905)
6: nativesdk-qemu-3.0.0-r0 do_unpack - 79s (pid 28730)
7: ca-certificates-20180409-r0 do_patch - 21s (pid 29845)
8: perl-5.24.4-r0 do_patch - 20s (pid 31668)
9: bind-9.11.4-r0 do_patch - 20s (pid 32441)
10: nativesdk-libxml2-2.9.8-r0 do_patch - 20s (pid 32447)
11: shared-mime-info-native-1.10-r0 do_prepare_recipe_sysroot - 5s (pid 32641)
12: bash-4.4.18-r0 do_patch - 5s (pid 348)
13: shared-mime-info-native-1.10-r0 do_patch - 4s (pid 602)
14: netbase-1_5.4-r0 do_unpack - 4s (pid 799)
15: groff-native-1.22.3-r0 do_patch - 4s (pid 727)
16: rsyslog-8.37.0-r0 do_unpack - 4s (pid 722)
17: e2fsprogs-1.44.3-r0 do_patch - 4s (pid 767)
18: gawk-4.2.1-r0 do_unpack - 4s (pid 813)
19: openssh-7.8p1+git-r0 do_unpack - 4s (pid 845)
20: dbus-1.12.10-r0 do_unpack - 4s (pid 972)
EOL_BUILD4
	sleep 2
	cat <<EOL_BUILD5
NOTE: Tasks Summary: Attempted 2802 tasks of which 14 didn't need to be rerun and all succeeded.

Summary: There was 1 WARNING message shown.
EOL_BUILD5
	mkdir -p tmp-glibc/deploy/images
	mkdir -p tmp-glibc/deploy/licenses
	mkdir -p tmp-glibc/deploy/rpm
	mkdir -p tmp-glibc/deploy/sdks
	touch tmp-glibc/deploy/sdks/wrlinux-small-10.18.44.4-glibc-x86_64-qemux86_64-wrlinux-image-glibc-core-sdk.host.manifest
	touch tmp-glibc/deploy/sdks/wrlinux-small-10.18.44.4-glibc-x86_64-qemux86_64-wrlinux-image-glibc-core-sdk.sh
	touch tmp-glibc/deploy/sdks/wrlinux-small-10.18.44.4-glibc-x86_64-qemux86_64-wrlinux-image-glibc-core-sdk.target.manifest
	touch tmp-glibc/deploy/sdks/wrlinux-small-10.18.44.4-glibc-x86_64-qemux86_64-wrlinux-image-glibc-core-sdk.testdata.json

else 
	cat <<EOFHELP
Usage: bitbake [options] [recipename/target recipe:do_task ...]

    Executes the specified task (default is 'build') for a given set of target recipes (.bb files).
    It is assumed there is a conf/bblayers.conf available in cwd or in BBPATH which
    will provide the layer, BBFILES and other configuration information.

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -b BUILDFILE, --buildfile=BUILDFILE
                        Execute tasks from a specific .bb recipe directly.
                        WARNING: Does not handle any dependencies from other
                        recipes.
  -k, --continue        Continue as much as possible after an error. While the
                        target that failed and anything depending on it cannot
                        be built, as much as possible will be built before
                        stopping.
  -f, --force           Force the specified targets/task to run (invalidating
                        any existing stamp file).
  -c CMD, --cmd=CMD     Specify the task to execute. The exact options
                        available depend on the metadata. Some examples might
                        be 'compile' or 'populate_sysroot' or 'listtasks' may
                        give a list of the tasks available.
  -C INVALIDATE_STAMP, --clear-stamp=INVALIDATE_STAMP
                        Invalidate the stamp for the specified task such as
                        'compile' and then run the default task for the
                        specified target(s).
  -r PREFILE, --read=PREFILE
                        Read the specified file before bitbake.conf.
  -R POSTFILE, --postread=POSTFILE
                        Read the specified file after bitbake.conf.
  -v, --verbose         Enable tracing of shell tasks (with 'set -x'). Also
                        print bb.note(...) messages to stdout (in addition to
                        writing them to ${T}/log.do_<task>).
  -D, --debug           Increase the debug level. You can specify this more
                        than once. -D sets the debug level to 1, where only
                        bb.debug(1, ...) messages are printed to stdout; -DD
                        sets the debug level to 2, where both bb.debug(1, ...)
                        and bb.debug(2, ...) messages are printed; etc.
                        Without -D, no debug messages are printed. Note that
                        -D only affects output to stdout. All debug messages
                        are written to ${T}/log.do_taskname, regardless of the
                        debug level.
  -q, --quiet           Output less log message data to the terminal. You can
                        specify this more than once.
  -n, --dry-run         Don't execute, just go through the motions.
  -S SIGNATURE_HANDLER, --dump-signatures=SIGNATURE_HANDLER
                        Dump out the signature construction information, with
                        no task execution. The SIGNATURE_HANDLER parameter is
                        passed to the handler. Two common values are none and
                        printdiff but the handler may define more/less. none
                        means only dump the signature, printdiff means compare
                        the dumped signature with the cached one.
  -p, --parse-only      Quit after parsing the BB recipes.
  -s, --show-versions   Show current and preferred versions of all recipes.
  -e, --environment     Show the global or per-recipe environment complete
                        with information about where variables were
                        set/changed.
  -g, --graphviz        Save dependency tree information for the specified
                        targets in the dot syntax.
  -I EXTRA_ASSUME_PROVIDED, --ignore-deps=EXTRA_ASSUME_PROVIDED
                        Assume these dependencies don't exist and are already
                        provided (equivalent to ASSUME_PROVIDED). Useful to
                        make dependency graphs more appealing
  -l DEBUG_DOMAINS, --log-domains=DEBUG_DOMAINS
                        Show debug logging for the specified logging domains
  -P, --profile         Profile the command and save reports.
  -u UI, --ui=UI        The user interface to use (knotty, ncurses or
                        toasterui - default knotty).
  --token=XMLRPCTOKEN   Specify the connection token to be used when
                        connecting to a remote server.
  --revisions-changed   Set the exit code depending on whether upstream
                        floating revisions have changed or not.
  --server-only         Run bitbake without a UI, only starting a server
                        (cooker) process.
  -B BIND, --bind=BIND  The name/address for the bitbake xmlrpc server to bind
                        to.
  -T SERVER_TIMEOUT, --idle-timeout=SERVER_TIMEOUT
                        Set timeout to unload bitbake server due to
                        inactivity, set to -1 means no unload, default:
                        Environment variable BB_SERVER_TIMEOUT.
  --no-setscene         Do not run any setscene tasks. sstate will be ignored
                        and everything needed, built.
  --setscene-only       Only run setscene tasks, don't run any real tasks.
  --remote-server=REMOTE_SERVER
                        Connect to the specified server.
  -m, --kill-server     Terminate any running bitbake server.
  --observe-only        Connect to a server as an observing-only client.
  --status-only         Check the status of the remote bitbake server.
  -w WRITEEVENTLOG, --write-log=WRITEEVENTLOG
                        Writes the event log of the build to a bitbake event
                        json file. Use '' (empty string) to assign the name
                        automatically.
  --runall=RUNALL       Run the specified task for any recipe in the taskgraph
                        of the specified target (even if it wouldn't otherwise
                        have run).
  --runonly=RUNONLY     Run only the specified task within the taskgraph of
                        the specified targets (and any task dependencies those
                        tasks may have).
EOFHELP

fi


